### ISSUE TITLE
Phoneinfo In Termux

### ISSUE THREAD

**Issue by hackerspunk** [termuxhackers-id/SIGIT#5]
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/sigit", line 549, in <module>
    if len(arg) == 1: menu()
  File "/data/data/com.termux/files/usr/bin/sigit", line 79, in menu
    mainmenu()
  File "/data/data/com.termux/files/usr/bin/sigit", line 87, in mainmenu
    elif cmd in ("1","01"): userrecon()
  File "/data/data/com.termux/files/usr/bin/sigit", line 310, in userrecon
    menu()
  File "/data/data/com.termux/files/usr/bin/sigit", line 79, in menu
    mainmenu()
  File "/data/data/com.termux/files/usr/bin/sigit", line 91, in mainmenu
    elif cmd in ("5","05"): phoneinfo()
  File "/data/data/com.termux/files/usr/bin/sigit", line 151, in phoneinfo
    print(f"{space}{b}-{w} Type    : {y}{res['phone_type']}{w}")
KeyError: 'phone_type'

`script issue probably` kind check out and push a update

**Comment by termuxhackers-id** [comment]
thankx for report, i have been fix this issue

**Comment by netslutter** [comment]
> thx for report, i have been [solved](https://github.com/termuxhackers-id/SIGIT/compare/f3e86a0cb1e8bf50b60c0618a2c2dfc4e8713198...b35731a0d72dba54ed3b256a4f83b58c364333fc?diff=unified) for this issues.
> try command: sigit update

Okay sir....and thanks for your response
